import React from 'react';
import { Character } from '../types';
import { X, Bot } from 'lucide-react';
import { motion } from 'framer-motion';

// Fix TS errors with framer-motion props
const MotionDiv = motion.div as any;

interface LoreModalProps {
  isOpen: boolean;
  onClose: () => void;
  isLoading: boolean;
  lore: string | null;
  character: Character | null;
}

const LoreModal: React.FC<LoreModalProps> = ({ isOpen, onClose, isLoading, lore, character }) => {
  if (!isOpen || !character) return null;

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4">
      <div className="absolute inset-0 bg-black/80 backdrop-blur-sm" onClick={onClose}></div>
      <MotionDiv 
        initial={{ scale: 0.9, opacity: 0 }}
        animate={{ scale: 1, opacity: 1 }}
        exit={{ scale: 0.9, opacity: 0 }}
        className="bg-slate-900 border border-slate-700 rounded-2xl w-full max-w-sm p-6 relative z-10 shadow-2xl"
      >
        <button 
          onClick={onClose}
          className="absolute top-4 right-4 text-slate-400 hover:text-white"
        >
          <X size={20} />
        </button>

        <div className="flex items-center gap-3 mb-4">
           <div className={`w-12 h-12 rounded-full bg-gradient-to-br ${character.themeColor} flex items-center justify-center`}>
              <Bot className="text-white" size={24} />
           </div>
           <div>
             <h3 className="text-lg font-display font-bold text-white">Muse AI</h3>
             <p className="text-xs text-slate-400">Generated Lore</p>
           </div>
        </div>

        <div className="min-h-[100px] flex items-center justify-center">
           {isLoading ? (
             <div className="flex flex-col items-center gap-2">
               <div className="w-6 h-6 border-2 border-indigo-500 border-t-transparent rounded-full animate-spin"></div>
               <span className="text-xs text-slate-400 animate-pulse">Summoning creativity...</span>
             </div>
           ) : (
             <p className="text-slate-200 text-sm leading-relaxed italic">
               "{lore}"
             </p>
           )}
        </div>
        
        {!isLoading && (
            <div className="mt-4 pt-4 border-t border-slate-800 text-center">
                <p className="text-[10px] text-slate-500">Content generated by Google Gemini</p>
            </div>
        )}
      </MotionDiv>
    </div>
  );
};

export default LoreModal;